# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExampleYWProfile' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExampleYWProfile

  target 'ExampleYWProfileTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExampleYWProfileUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'YWNamePlaceholder', :path => '~/Documents/Github/YWNamePlaceholder'

end
